import React, { Suspense } from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
// Importing index.css here is crucial so Vite knows to bundle it into the output style.css
import './index.css'

// @ts-ignore
import { app } from "/scripts/app.js";

function loadStylesheet() {
  const link = document.createElement('link')
  link.rel = 'stylesheet'
  link.type = 'text/css'
  // The style.css is generated by Vite alongside main.js.
  // import.meta.url resolves to the location of main.js at runtime.
  const cssName = './style.css';
  link.href = new URL(cssName, import.meta.url).href
  document.head.appendChild(link)
}

// --- Helper: Draggable Button Logic ---
function createDraggableButton() {
  // Prevent duplicate buttons
  if (document.getElementById("comfy-workflow-agent-button")) return;

  const button = document.createElement("button");
  button.textContent = "SG WorkflowAgent";
  button.id = "comfy-workflow-agent-button";
  button.style.cssText = `
      position: fixed;
      top: 10px;
      right: 10px;
      z-index: 9999;
      background: linear-gradient(90deg, #4f46e5, #7c3aed);
      color: white;
      border: none;
      padding: 8px 16px;
      border-radius: 20px;
      cursor: pointer;
      font-weight: bold;
      font-family: 'Inter', sans-serif;
      font-size: 14px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
      transition: transform 0.1s;
      user-select: none;
  `;

  document.body.appendChild(button);

  let isDragging = false;
  let startX = 0;
  let startY = 0;
  let initialLeft = 0;
  let initialTop = 0;
  let hasMoved = false;

  const onMouseDown = (e: MouseEvent) => {
      if (e.button !== 0) return; // Only left click
      isDragging = true;
      hasMoved = false;
      startX = e.clientX;
      startY = e.clientY;

      const rect = button.getBoundingClientRect();
      initialLeft = rect.left;
      initialTop = rect.top;

      // Switch to manual positioning
      button.style.right = 'auto';
      button.style.bottom = 'auto';
      button.style.left = `${initialLeft}px`;
      button.style.top = `${initialTop}px`;

      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
      e.preventDefault();
  };

  const onMouseMove = (e: MouseEvent) => {
      if (!isDragging) return;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;

      if (Math.abs(dx) > 2 || Math.abs(dy) > 2) {
          hasMoved = true;
      }

      button.style.transform = 'scale(1.05)';
      button.style.left = `${initialLeft + dx}px`;
      button.style.top = `${initialTop + dy}px`;
  };

  const onMouseUp = () => {
      isDragging = false;
      button.style.transform = 'scale(1)';
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);

      if (!hasMoved) {
          // Dispatch event to toggle the React App window
          const event = new CustomEvent("comfy-copilot-toggle");
          window.dispatchEvent(event);
      }
  };

  button.addEventListener('mousedown', onMouseDown);
}

// --- Main Extension Definition ---
const ext = {
  name: 'Comfy.WorkflowAgent',

  async setup() {
    console.log('🤖 Comfy Workflow Agent: Setup started');

    // 1. Inject Styles
    loadStylesheet();

    // 2. Create Root Container for React App
    // We use a dedicated root div that overlays the screen but allows clicks to pass through
    const rootId = "comfy-workflow-agent-root";
    let rootElement = document.getElementById(rootId);

    if (!rootElement) {
        rootElement = document.createElement("div");
        rootElement.id = rootId;
        rootElement.style.position = "fixed";
        rootElement.style.top = "0";
        rootElement.style.left = "0";
        rootElement.style.width = "100vw";
        rootElement.style.height = "100vh";
        rootElement.style.zIndex = "10000"; // High z-index to be above ComfyUI menu
        rootElement.style.pointerEvents = "none"; // Allow clicks to pass through to canvas
        rootElement.style.overflow = "hidden";
        document.body.appendChild(rootElement);
    }

    // 3. Create the toggle button
    createDraggableButton();

    // 4. Mount the React Application
    const root = ReactDOM.createRoot(rootElement);
    root.render(
      <React.StrictMode>
        <Suspense fallback={null}>
          <App />
        </Suspense>
      </React.StrictMode>
    );
  }
};

// --- Register Extension ---
// This uses the imported 'app' instance from ComfyUI scripts
app.registerExtension(ext);
